---
- name: install Goss
  become: yes
  become_user: root
  get_url:
    url: https://github.com/aelsabbahy/goss/releases/download/v0.3.7/goss-linux-amd64
    dest: /usr/bin/goss
    mode: +rx
- name: copy Goss test file over to remote
  copy:
    src: "{{ caller_directory }}/goss.yml"
    dest: ~/goss.yml
    mode: preserve
- name: execute Goss test and save results
  goss:
    path: ~/goss.yml
    format: "{{ results_format }}"
    output_file: ~/results
- name: copy results back to control node
  fetch:
    src: ~/results
    dest: "{{ lookup('env','PWD') }}/{{ caller_name }}_results"
    flat: yes
